- name: Deploy Bastion for UPI
  import_tasks: deploy_bastion_upi.yml
  when: ocp4_aio_deploy_type == 'upi'

- name: Deploy Bastion for IPI
  import_tasks: deploy_bastion_ipi.yml
  when: ocp4_aio_deploy_type == 'ipi'

- name: Deploy Bastion for SNO
  import_tasks: deploy_bastion_sno.yml
  when: ocp4_aio_deploy_type == 'sno'

- name: Prepare Guacamole prereqs on bastion
  import_tasks: prep_guac.yml
  when: ocp4_aio_deploy_guacamole
